const fs = require('fs');

const targetFile = '/Users/hugogarcez/Documents/promp/agente-promp/src/pages/Settings.jsx';
let content = fs.readFileSync(targetFile, 'utf8');

const lines = [
    '                        {/* PROMP API INTEGRATION CARD */}',
    '                        <div style={{ padding: "24px", border: "1px solid #10B981", borderRadius: "var(--radius-md)", background: "#F0FDF4", marginBottom: "32px" }}>',
    '                            <h3 style={{ fontSize: "16px", fontWeight: 600, color: "#059669", marginBottom: "8px" }}>Integração Automática Promp</h3>',
    '                            <p style={{ color: "#047857", fontSize: "14px", marginBottom: "16px" }}>',
    '                                Conecte-se globalmente ao seu Tenant da Promp e depois vincule este agente aos canais desejados.',
    '                            </p>',
    '',
    '                            {!isPrompConnected ? (',
    '                                <div style={{ display: "flex", gap: "12px", alignItems: "flex-end" }}>',
    '                                    <div style={{ flex: 1 }}>',
    '                                        <label style={{ display: "block", marginBottom: "8px", fontSize: "14px", fontWeight: 500, color: "#047857" }}>Identidade do Tenant (CPF/CNPJ)</label>',
    '                                        <input',
    '                                            type="text"',
    '                                            placeholder="000.000.000-00"',
    '                                            id="prompIdentityInput"',
    '                                            style={{',
    '                                                width: "100%", padding: "10px",',
    '                                                borderRadius: "var(--radius-md)",',
    '                                                border: "1px solid #10B981",',
    '                                                background: "white"',
    '                                            }}',
    '                                        />',
    '                                    </div>',
    '                                    <button',
    '                                        onClick={async () => {',
    '                                            const identity = document.getElementById("prompIdentityInput").value;',
    '                                            if (!identity) return alert("Digite a identidade (CPF/CNPJ).");',
    '',
    '                                            try {',
    '                                                const token = localStorage.getItem("token");',
    '                                                const res = await fetch("/api/promp/connect", {',
    '                                                    method: "POST",',
    '                                                    headers: {',
    '                                                        "Content-Type": "application/json",',
    '                                                        "Authorization": `Bearer ${token}`',
    '                                                    },',
    '                                                    body: JSON.stringify({ identity })',
    '                                                });',
    '',
    '                                                const data = await res.json();',
    '                                                if (res.ok) {',
    '                                                    alert("Tenant conectado com sucesso!");',
    '                                                    setIsPrompConnected(true);',
    '                                                } else {',
    '                                                    alert(data.message || "Erro ao conectar.");',
    '                                                }',
    '                                            } catch (e) {',
    '                                                alert("Erro de conexão.");',
    '                                            }',
    '                                        }}',
    '                                        style={{',
    '                                            background: "#10B981",',
    '                                            color: "white",',
    '                                            padding: "10px 20px",',
    '                                            borderRadius: "var(--radius-md)",',
    '                                            fontWeight: 600,',
    '                                            cursor: "pointer",',
    '                                            border: "none",',
    '                                            height: "42px"',
    '                                        }}',
    '                                    >',
    '                                        Conectar Tenant',
    '                                    </button>',
    '                                </div>',
    '                            ) : (',
    '                                <div style={{ borderTop: "1px solid #10B981", paddingTop: "16px", marginTop: "16px" }}>',
    '                                    <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "24px" }}>',
    '                                        <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>',
    '                                            <div style={{ width: "10px", height: "10px", background: "#059669", borderRadius: "50%" }}></div>',
    '                                            <strong style={{ color: "#059669" }}>Integração Global Ativa</strong>',
    '                                        </div>',
    '                                        <button',
    '                                            onClick={() => setIsPrompConnected(false)}',
    '                                            style={{',
    '                                                border: "1px solid #059669",',
    '                                                background: "transparent",',
    '                                                color: "#059669",',
    '                                                padding: "6px 12px",',
    '                                                borderRadius: "var(--radius-md)",',
    '                                                fontSize: "12px",',
    '                                                fontWeight: 600,',
    '                                                cursor: "pointer"',
    '                                            }}',
    '                                        >',
    '                                            Trocar Tenant',
    '                                        </button>',
    '                                    </div>',
    '',
    '                                    <h4 style={{ fontSize: "15px", fontWeight: 600, color: "#059669", marginBottom: "12px" }}>Canais do Agente</h4>',
    '                                    <p style={{ fontSize: "13px", color: "#047857", marginBottom: "16px" }}>',
    '                                        Selecione os canais que o agente <b>{agents.find(a => a.id === selectedAgentId)?.name || "Selecionado"}</b> deve responder:',
    '                                    </p>',
    '',
    '                                    {loadingChannels ? (',
    '                                        <div style={{ textAlign: "center", padding: "20px", color: "#059669" }}>Carregando canais...</div>',
    '                                    ) : (',
    '                                        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(250px, 1fr))", gap: "12px" }}>',
    '                                            {prompChannels.map(ch => {',
    '                                                const isLinked = ch.linkedAgents?.some(a => a.id === selectedAgentId);',
    '                                                return (',
    '                                                    <div key={ch.id} style={{',
    '                                                        background: "white",',
    '                                                        padding: "12px",',
    '                                                        borderRadius: "8px",',
    '                                                        border: isLinked ? "2px solid #10B981" : "1px solid #E5E7EB",',
    '                                                        display: "flex",',
    '                                                        justifyContent: "space-between",',
    '                                                        alignItems: "center"',
    '                                                    }}>',
    '                                                        <div style={{ overflow: "hidden" }}>',
    '                                                            <div style={{ fontWeight: 600, fontSize: "14px", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{ch.name}</div>',
    '                                                            <div style={{ fontSize: "11px", color: "#6B7280" }}>{ch.type.toUpperCase()} | {ch.status}</div>',
    '                                                        </div>',
    '                                                        <button',
    '                                                            onClick={() => toggleChannelLink(ch, isLinked)}',
    '                                                            style={{',
    '                                                                padding: "4px 8px",',
    '                                                                borderRadius: "4px",',
    '                                                                fontSize: "11px",',
    '                                                                fontWeight: 700,',
    '                                                                cursor: "pointer",',
    '                                                                border: "none",',
    '                                                                background: isLinked ? "#FEE2E2" : "#D1FAE5",',
    '                                                                color: isLinked ? "#B91C1C" : "#065F46"',
    '                                                            }}',
    '                                                        >',
    '                                                            {isLinked ? "Desvincular" : "Vincular"}',
    '                                                        </button>',
    '                                                    </div>',
    '                                                );',
    '                                            })}',
    '                                            {prompChannels.length === 0 && <div style={{ color: "#047857", fontSize: "13px", fontStyle: "italic" }}>Nenhum canal encontrado. Verifique sua conta Promp.</div>}',
    '                                        </div>',
    '                                    )}',
    '                                </div>',
    '                            )}',
    '                        </div>'
];

const newIntegrationCard = lines.join('\\n');

const startMarker = '{/* PROMP API INTEGRATION CARD */}';
const endMarker = 'Ou utilize este URL';

const startIdx = content.indexOf(startMarker);
const endIdx = content.indexOf(endMarker);

if (startIdx !== -1 && endIdx !== -1) {
    const updatedContent = content.substring(0, startIdx) + newIntegrationCard + '\\n\\n                        ' + content.substring(endIdx);
    fs.writeFileSync(targetFile, updatedContent);
    console.log('Successfully updated Settings.jsx');
} else {
    console.log('Markers not found:', startIdx, endIdx);
}
